#!/usr/bin/env python3
"""Render scene-facts.md from claims.yaml + evidence.yaml. Do not hand-edit generated files."""
from __future__ import annotations

import pathlib
import sys

import yaml

ROOT = pathlib.Path(__file__).resolve().parents[2]
BANNER = "<!-- generated by research/scripts/generate_scene_facts.py; do not edit by hand -->\n"


def load(path: pathlib.Path):
    with path.open(encoding="utf-8") as f:
        return yaml.safe_load(f)


def render_scene_facts(evidence: dict, claims: dict) -> str:
    scene = evidence.get("scene") or {}
    scene_id = scene.get("scene_id") or claims.get("scene_id") or ""
    lines = [
        BANNER,
        f"# scene-facts — {scene_id}\n",
        "```yaml\n",
        f"scene_id: {scene_id}\n",
        f"effective_status: {claims.get('effective_status') or evidence.get('effective_status') or 'PILOT'}\n",
        f"evidence_eligible: {str(claims.get('evidence_eligible', False)).lower()}\n",
        f"qualification_eligible: {str(evidence.get('qualification_eligible', False)).lower()}\n",
        f"qualification_credit: {evidence.get('qualification_credit') or 'NONE'}\n",
        f"isolation_status: {evidence.get('isolation_status') or 'UNSET'}\n",
        f"adversarial_fixture: {evidence.get('adversarial_fixture') or (evidence.get('correction_2026_08_29') or {}).get('adversarial_fixture')}\n",
        f"reproducibility: {evidence.get('reproducibility') or (evidence.get('correction_2026_08_29') or {}).get('reproducibility')}\n",
        f"live_original_fact_count: {claims.get('live_original_fact_count', 0)}\n",
        f"confirmed_count: {claims.get('confirmed_count', 0)}\n",
        "generated_from: claims.yaml\n",
        "```\n\n",
    ]
    hist = claims.get("historical_isolation") or evidence.get("historical_isolation_run") or {}
    if hist:
        commit = hist.get("commit") or ""
        lines.append("历史隔离产物不在工作树。")
        if commit:
            lines.append(f"原文：`git show {commit}:research/scenes/{scene_id}/scene-facts.md`。")
        lines.append("本文件只反映 `claims.yaml` 的 live 行与 Researcher notes。\n\n")
    live = [
        c
        for c in (claims.get("claims") or [])
        if isinstance(c, dict) and c.get("effective_status") == "ACTIVE"
    ]
    lines.append("## Live FactClaims\n\n")
    if not live:
        lines.append("无 ACTIVE FactClaim。\n\n")
    else:
        for c in live:
            rids = ", ".join(c.get("retrieval_ids") or [])
            lines.append(
                f"- **[{c.get('id')}] [{c.get('kind')}|{c.get('grade')}]** {c.get('text')} ({rids})\n"
            )
        lines.append("\n")
    notes = claims.get("researcher_notes") or []
    if notes:
        lines.append("## Researcher notes（不是 FactClaim）\n\n")
        for n in notes:
            rids = ", ".join(n.get("retrieval_ids") or [])
            grade = n.get("grade")
            tag = f"RESEARCHER_NOTE|{grade}" if grade else "RESEARCHER_NOTE"
            lines.append(f"- **[{n.get('id')}] [{tag}]** {n.get('text')} ({rids})\n")
        lines.append("\n")
    mapping = claims.get("element_mapping") or {}
    if mapping:
        lines.append("## Element mapping\n\n")
        for eid, row in mapping.items():
            if isinstance(row, dict):
                lines.append(f"- **{eid}** `{row.get('effective_status')}`: {row.get('note') or ''}\n")
            else:
                lines.append(f"- **{eid}** {row}\n")
        lines.append("\n")
    timeline = (scene.get("timeline") or {})
    if timeline:
        lines.append("## Timeline (scene card, not live FactClaim)\n\n")
        lines.append(f"status: {timeline.get('status')}\n\n")
        for name, branch in (timeline.get("branches") or {}).items():
            if isinstance(branch, dict):
                extra = " **not canonical**" if branch.get("not_canonical_scene_definition") else ""
                lines.append(f"- {name}: {branch.get('label')}{extra}\n")
        lines.append("\n")
    return "".join(lines)


def generate_one(scene_dir: pathlib.Path) -> None:
    evidence = load(scene_dir / "evidence.yaml")
    claims = load(scene_dir / "claims.yaml")
    text = render_scene_facts(evidence, claims)
    (scene_dir / "scene-facts.md").write_text(text, encoding="utf-8")


def main() -> None:
    scenes = ROOT / "research" / "scenes"
    if len(sys.argv) > 1:
        targets = [pathlib.Path(p) for p in sys.argv[1:]]
    else:
        targets = [p.parent for p in sorted(scenes.glob("*/claims.yaml"))]
    for scene_dir in targets:
        generate_one(scene_dir)
        print(f"wrote {scene_dir / 'scene-facts.md'}")


if __name__ == "__main__":
    main()
